### ISSUE TITLE
winner function

### ISSUE THREAD

**Issue by hjc2** [TU-CSCI2322-FL22/solver-tic-tac-jose#42]
yields unfair ties

(tieTop ++ [(6,[(0,X),(1,X),(2,X)])] ++ [(7,[(0,X),(1,X),(2,X),(8,X)])] ++  [(8,[(0,X),(2,X),(8,X)])],(O,8)) -- shouldn't be a tie

**Comment by QLe13** [comment]
It is one the winner function or on the whoWins one?

**Comment by hjc2** [comment]
winner

**Comment by hjc2** [comment]
fixed
