### ISSUE TITLE
Duplicate (and not working?) function

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-tic-tac-jose#61]
https://github.com/TU-CSCI2322-FL22/solver-tic-tac-jose/blob/5dac73a29a2db5ac0e6df0011b7eeb8b6f0074b3/Solver.hs#L45-L57

`whoWillWin` uses `curOutcome`, which takes the current player into account. However, `whoWins` uses `compress`, which always favors X over O! That seems wrong. And yet, `whoWillWin` uses `whoWins` on it's children.

**Comment by hjc2** [comment]
compress is now neutral
